[project]
name = "btc-forecast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.4",
    "plotly>=6.0.1",
    "prophet>=1.1.6",
    "pyarrow>=19.0.1",
    "streamlit>=1.44.1",
    "yfinance>=0.2.55",
]
